version: '3.8'

services:
  bobapp-back:
    build: ./back
    container_name: bobapp-back
    ports:
      - "8080:8080"
    networks:
      - bobapp-net

  bobapp-front:
    build: ./front
    container_name: bobapp-front
    ports:
      - "3000:80"
    depends_on:
      - bobapp-back
    networks:
      - bobapp-net

networks:
  bobapp-net:
    driver: bridge
