name: CI - Tests Back-End

on:
  push:
    branches:
      - main
      - 2025.9
  pull_request:
    branches:
      - main
      - 2025.9

jobs:
  test-back:
    name: Tests du back-end (Spring Boot)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: 🔨 Build et tests Maven
        run: mvn clean verify

      - name: Génération du rapport JaCoCo
        run: mvn jacoco:report

      - name: Upload du rapport de couverture
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: back/target/site/jacoco/
