name: Analyse SonarCloud

on:
  push:
    branches:
      - main
      - 2025.9
  pull_request:
  workflow_dispatch:

jobs:
  sonarcloud:
    name: Analyse du code avec SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build du back-end
        working-directory: back
        run: mvn -B clean verify -DskipTests

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installation dépendances front
        working-directory: front
        run: npm install

      - name: Tests Angular + couverture
        working-directory: front
        run: npm run test -- --watch=false --code-coverage

      - name: Analyse SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}